#!/bin/sh

uci -q show system.@watchcat[0] || {
	uci add system watchcat
	uci set system.@watchcat[0].period=20
	uci set system.@watchcat[0].mode=ping
	uci set system.@watchcat[0].pinghosts=8.8.8.8
	uci set system.@watchcat[0].forcedelay=10
	uci commit
}


uci -q get wifimedia.@advance[0] || {
        uci batch <<EOF
        add wifimedia advance
        set wifimedia.@advance[0].level=-80
        set wifimedia.@advance[0].delays=8s	
        commit wifimedia
EOF
}
