#!/bin/sh

echo -e "live:x:1000:1000:live:/root:/bin/false" >>/etc/passwd
echo -e "live:*:0:0:99999:7:::" >>/etc/shadow
echo "*/10 * * * * /sbin/wifimedia/updates.sh" >>/etc/crontabs/live
######Cron job
echo "* * * * * /sbin/wifimedia/controller.sh checking" >>/etc/crontabs/root
echo "* * * * * /sbin/wifimedia/controller.sh remote_cfg" >>/etc/crontabs/root
echo "0 0 * * * /sbin/wifimedia/controller_srv.sh upgrade_srv" >>/etc/crontabs/root
/etc/init.d/cron start
/etc/init.d/cron enable
/sbin/wifimedia/updates.sh

uci -q get wifimedia.@advance[0] || {
        uci batch <<EOF
        add wifimedia advance
        commit wifimedia
EOF
}
