#!/bin/sh

#echo -e "ap:x:1000:1000:ap:/root:/bin/false" >>/etc/passwd
#echo -e "ap:*:0:0:99999:7:::" >>/etc/shadow
#echo "*/5 * * * * /etc/init.d/md_prerun start" >>/etc/crontabs/ap
#/etc/init.d/cron start
#/etc/init.d/cron enable