#!/bin/sh /etc/rc.common

START=9
STOP=12

boot() {
	/etc/init.d/network restart
	ifup lan
	if [ "$(uci -q get wifimedia.@lte[0].4glte)" -eq 0 ] || [ "$(uci -q get wifimedia.@lte[0].4glte)" = "" ];then
		echo 0 >/sys/class/gpio/power_usb3/value
	fi
	while true; do
    	ping -c1 -W1 8.8.8.8
    	if [ ${?} -eq 0 ]; then
      	  	break
   	else
        	sleep 1
    	fi
	done
	/sbin/wifimedia/controller.sh checking
	/sbin/wifimedia/controller.sh action_lan_wlan
	ifup wan && ifup lan
	#/sbin/wifimedia/controller.sh openvpn #Start openvpn fistboot
}

