#!/bin/sh /etc/rc.common

START=3
STOP=6

boot() {
    /etc/init.d/network restart
	# Wait for network up & running
	while true; do
    	ping -c1 -W1 8.8.8.8
    	if [ ${?} -eq 0 ]; then
      	  	break
   	else
        	sleep 1
    	fi
	done
	/sbin/wifimedia/controller.sh checking
	/sbin/wifimedia/controller.sh action_lan_wlan
}

