#!/bin/sh

rnd=`cat /dev/urandom | tr -dc 'A-Z' | head -c1`
model_hardware=$(cat /proc/cpuinfo | grep 'machine' | cut -f2 -d ":" | cut -b 10-50 | tr ' ' '_')
uci -q get system.@reset_all[0] || {
	uci batch <<-EOF
	add system reset_all
	set system.@reset_all[0]=reset_all
	commit system
EOF
}

###Sync
uci -q get wifimedia.@sync[0] || {
	uci batch <<-EOF
	add wifimedia sync
	set wifimedia.@sync[0]=sync
	set wifimedia.@sync[0].version=2.1.0
	#set wifimedia.@sync[0].domain="crm.wifimedia.com.vn"
	commit wifimedia
EOF
}

###Build Date
uci -q get wifimedia.@builddate[0] || {
	uci batch <<-EOF
	add wifimedia builddate
	set wifimedia.@builddate[0]=builddate
	set wifimedia.@builddate[0].date=05/10/2019
	commit wifimedia
EOF
}

uci -q get wifimedia.@wireless[0] || {
	uci batch <<-EOF
	add wifimedia wireless
	set wifimedia.@wireless[0]=wireless
	commit wifimedia
EOF
}
#change ver  for upgrade
uci set wifimedia.@sync[0].version=2.1.1
uci set wifimedia.@sync[0].rsn=2.6
uci set wifimedia.@sync[0].sw=2.5
uci set wifimedia.@sync[0].button=2.4
uci set wifimedia.@sync[0].ftrs=2.3
uci set wifimedia.@sync[0].passwdwifi=2.2
uci set wifimedia.@sync[0].passwd=2.1
uci set wifimedia.@advance[0].wireless_cfg=0
uci commit wifimedia

uci batch <<-EOF
	set system.@system[0]=system
	set system.@system[0].hostname="WIFIMEDIA"
	set system.@system[0].zonename='Asia/Ho Chi Minh'
	set system.@system[0].timezone=ICT-7
EOF

if [ "$model_hardware" == "AC51U" ] || [ "$model_hardware" == "CF-E355AC_v2" ] || [ "$model_hardware" == "TL-WR741ND_v4" ] || [ "$model_hardware" == "CF-E320N_v2" ] || [ "$model_hardware" == "TL-WR940N_v4" ] || [ "$model_hardware" == "TL-WR940N_v6" ] || [ "$model_hardware" == "TL-WR941N/ND_v6" ];then
	uci batch <<-EOF
		set network.lan.ipaddr=172.16.99.1
		#set network.lan.ipaddr=192.168.6.1 #set commit ipaddr for TPLink 940V3 WR841V11
		set network.wan.type=bridge
		delete network.globals
		set dhcp.lan.force=1
		set dhcp.lan.netmask=255.255.255.0
		add_list dhcp.lan.dhcp_option=6,8.8.8.8,8.8.4.4
		commit
	EOF

	uci batch <<-EOF
		set wireless.default_radio0.maxassoc=30
		set wireless.@wifi-iface[0].ssid=OPENWIFI
		#set wireless.@wifi-iface[0].ssid=PDA_$rnd
		#set wireless.@wifi-iface[0].encryption="psk2"
		#set wireless.@wifi-iface[0].key="123456A@$rnd"
		set wireless.radio0.disabled=0
		commit wireless
	EOF

fi

if [ "$model_hardware" == "TL-WR840N_v6" ] || [ "$model_hardware" == "TL-WR841N_v14" ] || [ "$model_hardware" == "TL-WR840N_v4" ] || [ "$model_hardware" == "TL-WR841N_v13" ] || [ "$model_hardware" == "TL-WR840N_v5" ];then
	uci batch <<-EOF
		set network.lan.ipaddr=192.168.5.1
		set network.wan.type=bridge
		delete network.globals
		set dhcp.lan.force=1
		set dhcp.lan.netmask=255.255.255.0
		add_list dhcp.lan.dhcp_option=6,8.8.8.8,8.8.4.4
		commit
	EOF

	uci batch <<-EOF
		set wireless.@wifi-iface[0].maxassoc=30
		#set wireless.@wifi-iface[0].ssid="LoopPos"
		#set wireless.@wifi-iface[0].ssid=WIFIMEDIA_$rnd
		set wireless.@wifi-iface[0].ssid=WIFIMEDIA.VN
		set wireless.@wifi-iface[0].encryption="psk2"
		#set wireless.@wifi-iface[0].key="loopposA@"
		#set wireless.@wifi-iface[0].disabled=0
		set wireless.@wifi-device[0].country=CN
		set wireless.@wifi-device[0].txpower=20
		set wireless.@wifi-device[0].channel=auto
		commit wireless
	EOF
	uci set wireless.@wifi-device[0].channel=auto
	uci commit
fi

if [ "$model_hardware" == "TL-WR840N_v4" ];then
	echo "TL-WR840N v4" >/etc/hardware
elif [ "$model_hardware" == "TL-WR741ND_v4" ];then
	echo "TL-WR740N v4" >/etc/hardware		
elif [ "$model_hardware" == "TL-WA901ND_v3" ];then
	echo "TL-WA901ND v3" >/etc/hardware
elif [ "$model_hardware" == "TL-WR841N_v13" ];then
	echo "TL-WR841N v13" >/etc/hardware
elif [ "$model_hardware" == "TL-WR940N_v4" ];then
	echo "TL-WR940N v5" >/etc/hardware
elif [ "$model_hardware" == "TL-WR940N_v6" ];then
	echo "TL-WR940N v6.1" >/etc/hardware
elif [ "$model_hardware" == "TL-WR941N/ND_v6" ];then
	echo "TL-WR940N v3" >/etc/hardware
elif [ "$model_hardware" == "TL-WR840N_v5" ];then
	echo "TL-WR840N v5" >/etc/hardware
elif [ "$model_hardware" == "TL-WR841N_v14" ];then
	echo "TL-WR841N v14" >/etc/hardware
elif [ "$model_hardware" == "TL-WR840N_v6" ];then
	echo "TL-WR840N v6" >/etc/hardware	
elif [ "$model_hardware" == "AC51U" ];then
	echo "AC700" >/etc/hardware	
elif [ "$model_hardware" == "CF-E355AC_v2" ];then
	echo "EAP35AC v2" >/etc/hardware
	uci set meshdesk.settings.id_if="eth1"
	uci commit meshdesk
elif [ "$model_hardware" == "CF-E320N_v2" ];then
	echo "EAP320v2" >/etc/hardware
	uci set meshdesk.settings.id_if="eth1"
	uci commit meshdesk
fi

#Add vitual SSID
#For abng
#uci -q get wireless.@wifi-iface[1] || {
#        uci batch <<EOF
#        add wireless wifi-iface
#        set wireless.@wifi-iface[1].device=radio0
#        set wireless.@wifi-iface[1].mode=ap
#        set wireless.@wifi-iface[1].network=lan
#        set wireless.@wifi-iface[1].ssid=OPENWIFIx2
#		set wireless.@wifi-iface[1].disabled=1
#        commit wireless
#EOF
#}


#uci batch <<-EOF
#	set wireless.radio0.channel=157
	#set wireless.@wifi-device[-1].channel=6
	#set wireless.radio0.disabled=0
	#set wireless.radio1.disabled=0
#5G
#	set wireless.default_radio0.ssid="OPENWIFI"
#	set wireless.default_radio0.macaddr=60:A5:EF:63:E7:6D
#	#set wireless.default_radio1.ssid="VIETNAM POST"
#	#set wireless.default_radio1.maxassoc=30
#	#set wireless.radio0.macaddr=$(cat /sys/class/ieee80211/phy0/macaddress)
#	add_list wireless.radio0.ht_capab="SHORT-GI-20"
#	add_list wireless.radio0.ht_capab="SHORT-GI-40"
#	add_list wireless.radio0.ht_capab="RX-STBC1"
#	add_list wireless.radio0.ht_capab="DSSS_CCK-40"
#	set wireless.radio0.country="CN"
#	set wireless.radio0.txpower=20
#	set wireless.radio0.htmode=VHT40
#	set wireless.radio1.txpower=20
#	commit wireless
#EOF
#enable wifi
uci set wireless.radio0.disabled="0"
uci commit wireless
wifi
#for hwmode n ac
uci batch <<-EOF
	delete network.wan6
	commit network
EOF

uci batch <<-EOF
	set firewall.@zone[1].input="ACCEPT"
	commit firewall
	EOF
	
NET_ID="private"
FW_ZONE="private"
IFNAME="eth0.300" #VLAN1
uci batch << EOF
	set network.${NET_ID}=interface
	set network.${NET_ID}.ifname=${IFNAME}
	set network.${NET_ID}.proto=static
	set network.${NET_ID}.type=bridge
	set network.${NET_ID}.ipaddr=10.68.255.1
	set network.${NET_ID}.netmask=255.255.255.0
	set dhcp.${NET_ID}=dhcp
	set dhcp.${NET_ID}.interface=${NET_ID}
	set dhcp.${NET_ID}.start=100
	set dhcp.${NET_ID}.leasetime=1h
	set dhcp.${NET_ID}.limit=150
	set firewall.${FW_ZONE}=zone
	set firewall.${FW_ZONE}.name=${FW_ZONE}
	set firewall.${FW_ZONE}.network=${NET_ID}
	set firewall.${FW_ZONE}.forward=ACCEPT
	set firewall.${FW_ZONE}.output=ACCEPT
	set firewall.${FW_ZONE}.input=ACCEPT 
	set firewall.${FW_ZONE}_fwd=forwarding
	set firewall.${FW_ZONE}_fwd.src=${FW_ZONE}
	set firewall.${FW_ZONE}_fwd.dest=wan
	set firewall.${FW_ZONE}_dhcp=rule
	set firewall.${FW_ZONE}_dhcp.name=${FW_ZONE}_DHCP
	set firewall.${FW_ZONE}_dhcp.src=${FW_ZONE}
	set firewall.${FW_ZONE}_dhcp.target=ACCEPT
	set firewall.${FW_ZONE}_dhcp.proto=udp
	set firewall.${FW_ZONE}_dhcp.dest_port=67-68
	set firewall.${FW_ZONE}_dns=rule
	set firewall.${FW_ZONE}_dns.name=${FW_ZONE}_DNS
	set firewall.${FW_ZONE}_dns.src=${FW_ZONE}
	set firewall.${FW_ZONE}_dns.target=ACCEPT
	set firewall.${FW_ZONE}_dns.proto=tcpudp
	set firewall.${FW_ZONE}_dns.dest_port=53
	set dhcp.${NET_ID}.force=1
	set dhcp.${NET_ID}.netmask=255.255.255.0
	add_list dhcp.${NET_ID}.dhcp_option=6,8.8.8.8,8.8.4.4
	commit firewall
	commit network
	commit dhcp
EOF
	
#Password	
echo -e "admin:x:1000:1000:admin:/root:/bin/false" >>/etc/passwd
echo -e "admin:*:0:0:99999:7:::" >>/etc/shadow
echo -e "wifimedia\nwifimedia" | passwd admin

echo -e "wifimedia:x:0:0:wifimedia:/root:/bin/ash" >>/etc/passwd
echo -e "wifimedia:*:0:0:99999:7:::" >>/etc/shadow
echo -e "09465670089\n09465670089" | passwd wifimedia

#Change password for root
word=$(cat /sys/class/ieee80211/phy0/macaddress | cut -c  10,11,13,14,16,17 | sed 's/://g' |awk '{print $1}'|tr a-z A-Z)
pwd=$(echo -n $word | md5sum | awk '{print $1}')
#echo -e "$pwd\n$pwd" | passwd root
echo -e "wifimedia\nwifimedia" | passwd root
#End

#Info
CODENAME="wifimedia"
if [ -f "/etc/codename" ]; then
	source /etc/codename
fi
uci batch <<-EOF
	delete wifimedia.Version
	set wifimedia.Version=version
	set wifimedia.Version.ver=$CODENAME
	commit wifimedia
EOF

source /etc/openwrt_release
rm -f /etc/openwrt_release
DISTRIB_DESCRIPTION=$(uci get wifimedia.Version.ver)""
echo 'DISTRIB_ID="'"$DISTRIB_ID"'"' >> /etc/openwrt_release
echo 'DISTRIB_RELEASE="'"$DISTRIB_RELEASE"'"' >> /etc/openwrt_release
echo 'DISTRIB_REVISION="'" "'"' >> /etc/openwrt_release
echo 'DISTRIB_CODENAME="'"$DISTRIB_CODENAME"'"' >> /etc/openwrt_release
echo 'DISTRIB_TARGET="'"$DISTRIB_TARGET"'"' >> /etc/openwrt_release
echo 'DISTRIB_DESCRIPTION="'"$DISTRIB_DESCRIPTION"'"' >> /etc/openwrt_release

#rm -f /etc/privoxy/default.action
#rm -f /etc/privoxy/default.filter

#chmod a+x /sbin/wifimedia/*.sh
/etc/init.d/system reload
/etc/init.d/led reload

######Cron job
echo "* * * * * /sbin/wifimedia/controller.sh checking" >>/etc/crontabs/root
#echo "* * * * * /sbin/wifimedia/controller.sh remote_cfg" >>/etc/crontabs/root
#echo "0 0 * * * /sbin/wifimedia/controller_srv.sh upgrade_srv" >>/etc/crontabs/root

/etc/init.d/cron start
/etc/init.d/cron enable
/etc/init.d/wifimedia_upgrade enable

uci set dhcp.lan.start=99
uci set dhcp.lan.limit=100
uci set dhcp.lan.leasetime=1h
uci commit dhcp
#SYNCH TIME
uci batch <<-EOF
	del system.ntp
	set system.ntp=timeserver
        add_list system.ntp.server='0.asia.pool.ntp.org'
        add_list system.ntp.server='1.asia.pool.ntp.org'
        add_list system.ntp.server='2.asia.pool.ntp.org'
        add_list system.ntp.server='3.asia.pool.ntp.org'
	set system.ntp.enabled=1
	set system.ntp.enable_server=1
	commit system
EOF
/etc/init.d/sysntpd start >/dev/null
##LED XIAOMI-MIWIFI
#uci batch <<-EOF
#	set system.led_power.name='power'
#	set system.led_power.default='1'
#	set system.led_power.trigger='netdev'
#	set system.led_power.dev='br-wan'
#	set system.led_power.mode='link tx rx'
#	set system.led_power.sysfs='xiaomi:blue:status'
#	commit system
#EOF
uci set luci.diag.dns="google.com.vn"
uci set luci.diag.ping="google.com.vn"
uci set luci.diag.route="google.com.vn"

#Change ssh
uci batch <<-EOF
	set dropbear.@dropbear[0].Port=2702
	commit dropbear
EOF
touch /etc/opt/wfm_status
rm -f /etc/banner
mv /etc/banner_ /etc/banner
/etc/init.d/dropbear restart
/etc/init.d/network restart
/etc/init.d/led reload
#/etc/init.d/watchcat start #start watchcat
rm -f /root/advance_model.lua
rm -f /root/gw_index.htm
rm -f /root/wifi_overview.htm
chmod +x /sbin/wifimedia/*
wifi up
#rm -f /etc/uci-defaults/wifimedia
#sleep 5 && reboot
