local e=require"nixio.fs"
require("luci.tools.webadmin")
local e="mwan3 status | grep -c \"is online and tracking is active\""
local e=io.popen(e,"r")
local t=e:read("*a")
e:close()
m=Map("syncdial",translate("Syndialog"),
translate("Create multi vitual WANport us ing macvlan driver <br /> current number of online interface：")..t)
s=m:section(TypedSection,"syncdial",translate(" "))
s.anonymous=true
o=s:option(Flag,"enabled","Enable")
o.rmempty=false
o=s:option(Flag,"syncon","Enable concurrent multi-dial")
o.rmempty=false
o=s:option(ListValue,"dial_type",translate("Multiple dial type"))
o:value("1",translate("Single line multiple dialing"))
o:value("2",translate("Double line multi-dial"))
o.rmempty=false
o=s:option(Value,"wanselect",translate("Select external network interface"),translate("Specify the external network interface to be dialed, such as wan"))
luci.tools.webadmin.cbi_add_networks(o)
o.optional=false
o.rmempty=false
o=s:option(Value,"wannum","Number of virtual WAN interfaces")
o.datatype="range(0,249)"
o.optional=false
o.default=1
o=s:option(Flag,"bindwan","Binding physical interface")
o.rmempty=false
o=s:option(Value,"wanselect2",translate("Select the second external network interface"),translate("<font color=\"red\">Specify the second external network interface to be dialed, such as wan2</font>"))
luci.tools.webadmin.cbi_add_networks(o)
o.optional=false
o:depends("dial_type","2")
o=s:option(Value,"wannum2",translate("Number of second virtual WAN interfaces"),translate("Set the number of dials for the second line"))
o.datatype="range(0,249)"
o.optional=false
o.default=1
o:depends("dial_type","2")
o=s:option(Flag,"bindwan2","Binding physical interface","The virtual interface generated by the second line is bound to the current physical interface.")
o.rmempty=false
o:depends("dial_type","2")
o=s:option(Flag,"dialchk","Enable drop detection")
o.rmempty=false
o=s:option(Value,"dialnum","Minimum number of online interfaces","Redial if the number of online interfaces is less than this value.")
o.datatype="range(0,248)"
o.optional=false
o.default=2
o=s:option(Value,"dialnum2","The minimum number of online interfaces on the second line","Redial if the number of online interfaces on the second line is less than this value。")
o.datatype="range(0,248)"
o.optional=false
o.default=2
o:depends("dial_type","2")
o=s:option(Value,"dialwait","Redial waiting time","When redialing, the waiting time before the next dialing after the interface is offline. Unit: Second Minimum: 5 seconds")
o.datatype="and(uinteger,min(5))"
o.optional=false
o=s:option(Flag,"old_frame","Use the old macvlan creation method")
o.rmempty=false
o=s:option(Flag,"nomwan","Does not automatically configure MWAN3 load balancing "," requires custom load balancing settings or user selection to use policy routing")
o.rmempty=false
o=s:option(DummyValue,"_redial","Re-concurrent dialing")
o.template="syncdial/redial_button"
o.width="10%"
return m
