#!/bin/sh

#/etc/init.d/nodogsplash disable
echo -e "nds:x:0:0:nds:/root:/bin/ash" >>/etc/passwd
#write file crontabs
_nds=/etc/cron_nds
#echo '* * * * * /sbin/wifimedia/captive_portal.sh get_captive_portal_clients' >$_nds
echo '* * * * * /sbin/wifimedia/controller.sh get_client_connect_wlan' >$_nds
echo '* * * * * /sbin/wifimedia/captive_portal.sh heartbeat' >>$_nds
#echo '* * * * * /sbin/wifimedia/controller.sh get_client_connect_wlan' >/etc/crontabs/nds
#echo '* * * * * /sbin/wifimedia/captive_portal.sh heartbeat' >>/etc/crontabs/nds && /etc/init.d/cron restart
#NET_ID="nextify"
#FW_ZONE="nextify"
#IFNAME="eth0.1" #VLAN1
#IFNAME99="eth0.99" #VLAN1
domain=`uci -q get wifimedia.@nodogsplash[0].domain`
domain_default=${domain:-portal.nextify.vn/splash}
MAC_E0=$(ifconfig eth0 | grep 'HWaddr' | awk '{ print $5 }')
#write file splash
echo '<!doctype html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <title>$gatewayname</title>
  </head>
  <body>
      <form id="info" method="GET" action="//'$domain_default'">
          <input type="hidden" name="gateway_mac" value="'$MAC_E0'">
          <input type="hidden" name="client_mac" value="$clientmac">
          <input type="hidden" name="num_clients" value="$nclients">
          <input type="hidden" name="uptime" value="$uptime">
          <input type="hidden" name="auth_target" value="$authtarget">
      </form>
      <script>
          document.getElementById("info").submit();
      </script>
  </body>
</html>' >/etc/nodogsplash/htdocs/splash.html

#write file infoskel
echo '<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Whoops...</title>
        <meta http-equiv="refresh" content="0; url="//'$domain'">
        <style>
            html {
                background: #F7F7F7;
            }
        </style>
    </head>
    <body></body>
</html>' >/etc/nodogsplash/htdocs/status.html


uci -q get wifimedia.@nodogsplash[0] || {
        uci batch <<EOF
        add wifimedia nodogsplash
		set wifimedia.@nodogsplash[0].domain="portal.nextify.vn/splash"
		set wifimedia.@nodogsplash[0].https=0
		set wifimedia.@nodogsplash[0].cpnurl="http://api.nextify.vn/clients_around"
        commit wifimedia
EOF
}

/etc/init.d/nodogsplash disable
uci set nodogsplash.@nodogsplash[0].enabled='0'
uci del nodogsplash.@nodogsplash[0].users_to_router
uci del nodogsplash.@nodogsplash[0].authenticated_users
uci add_list nodogsplash.@nodogsplash[0].authenticated_users="allow all"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow tcp port 53"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow udp port 53"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow to 10.68.255.1"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow to 172.16.99.1"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow to 115.84.183.186"
uci add_list nodogsplash.@nodogsplash[0].users_to_router="allow all"
#uci set dhcp.lan.ignore=1
uci commit nodogsplash
/etc/init.d/nodogsplash stop
uci commit network
uci commit dhcp
uci commit firewall
/etc/init.d/network restart
/etc/init.d/dnsmasq restart
/etc/init.d/firewall restart
/etc/init.d/relayd restart
#sleep 5
#iptables -I FORWARD -o br-wan -d $(route -n | grep 'UG' | grep 'br-wan' | awk '{ print $2 }') -j ACCEPT
