#!/bin/sh

#/etc/init.d/nodogsplash disable
echo -e "nds:x:0:0:nds:/root:/bin/ash" >>/etc/passwd
#write file crontabs
_nds=/etc/cron_nds
echo '* * * * * /sbin/wifimedia/controller.sh get_captive_portal_clients' >$_nds
echo '*/5 * * * * /sbin/wifimedia/heartbeat.sh' >>$_nds
echo '* * * * * /sbin/wifimedia/controller.sh get_captive_portal_clients' >/etc/crontabs/nds
echo '*/5 * * * * /sbin/wifimedia/heartbeat.sh' >>/etc/crontabs/nds && /etc/init.d/cron restart
#NET_ID="nextify"
#FW_ZONE="nextify"
#IFNAME="eth0.1" #VLAN1
#IFNAME99="eth0.99" #VLAN1
domain=`uci -q get wifimedia.@nodogsplash[0].domain`
domain_default=${domain:-portal.nextify.vn/splash}
MAC_E0=$(ifconfig eth0 | grep 'HWaddr' | awk '{ print $5 }')
#write file splash
#write file splash
echo '<!doctype html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <title>$gatewayname</title>
  </head>
  <body>
      <form id="info" method="POST" action="//'$domain_default'">
          <input type="hidden" name="gateway_name" value="$gatewayname">
          <input type="hidden" name="gateway_mac" value="'$MAC_E0'">
          <input type="hidden" name="client_mac" value="$clientmac">
          <input type="hidden" name="num_clients" value="$nclients">
          <input type="hidden" name="uptime" value="$uptime">
          <input type="hidden" name="auth_target" value="$authtarget">
      </form>
      <script>
          document.getElementById("info").submit();
      </script>
  </body>
</html>' >/etc/nodogsplash/htdocs/splash.html

#write file infoskel
echo '<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Whoops...</title>
        <meta http-equiv="refresh" content="0; url="//'$domain'">
        <style>
            html {
                background: #F7F7F7;
            }
        </style>
    </head>
    <body></body>
</html>' >/etc/nodogsplash/htdocs/status.html


uci -q get wifimedia.@nodogsplash[0] || {
        uci batch <<EOF
        add wifimedia nodogsplash
		set wifimedia.@nodogsplash[0].domain="portal.nextify.vn/splash"
		set wifimedia.@nodogsplash[0].https=0
        commit wifimedia
EOF
}

#uci batch << EOF
#	set network.${NET_ID}=interface
#	set network.${NET_ID}.ifname=${IFNAME}
#	set network.${NET_ID}.proto=static
#	set network.${NET_ID}.type=bridge
#	set network.${NET_ID}.ipaddr=10.68.255.1
#	set network.${NET_ID}.netmask=255.255.255.0
#	set dhcp.${NET_ID}=dhcp
#	set dhcp.${NET_ID}.interface=${NET_ID}
#	set dhcp.${NET_ID}.start=100
#	set dhcp.${NET_ID}.leasetime=1h
#	set dhcp.${NET_ID}.limit=150
#	set dhcp.${NET_ID}.force=1
#	#set dhcp.${NET_ID}.ignore=1
#	set dhcp.${NET_ID}.netmask=255.255.255.0
#    add_list dhcp.${NET_ID}.dhcp_option=6,8.8.8.8,8.8.4.4	
#	set firewall.${FW_ZONE}=zone
#	set firewall.${FW_ZONE}.name=${FW_ZONE}
#	set firewall.${FW_ZONE}.network=${NET_ID}
#	set firewall.${FW_ZONE}.forward=ACCEPT
#	set firewall.${FW_ZONE}.output=ACCEPT
#	set firewall.${FW_ZONE}.input=ACCEPT 
#	set firewall.${FW_ZONE}_fwd=forwarding
#	set firewall.${FW_ZONE}_fwd.src=${FW_ZONE}
#	set firewall.${FW_ZONE}_fwd.dest=wan
#	set firewall.${FW_ZONE}_dhcp=rule
#	set firewall.${FW_ZONE}_dhcp.name=${FW_ZONE}_DHCP
#	set firewall.${FW_ZONE}_dhcp.src=${FW_ZONE}
#	set firewall.${FW_ZONE}_dhcp.target=ACCEPT
#	set firewall.${FW_ZONE}_dhcp.proto=udp
#	set firewall.${FW_ZONE}_dhcp.dest_port=67-68
#	set firewall.${FW_ZONE}_dns=rule
#	set firewall.${FW_ZONE}_dns.name=${FW_ZONE}_DNS
#	set firewall.${FW_ZONE}_dns.src=${FW_ZONE}
#	set firewall.${FW_ZONE}_dns.target=ACCEPT
#	set firewall.${FW_ZONE}_dns.proto=tcpudp
#	set firewall.${FW_ZONE}_dns.dest_port=53
#	#set network.${NET_ID}=interface
#	#set network.${NET_ID}.proto=relay
#	#set network.${NET_ID}.ipaddr=10.68.255.1	
#	#add_list network.${NET_ID}.network=${NET_ID}
#	#add_list network.${NET_ID}.network=wan	
#	commit
#EOF

#NET_RELAY=local
#uci batch << EOF
#	set network.${NET_RELAY}=interface
#	set network.${NET_RELAY}.proto=relay
#	#set network.${NET_RELAY}.forward_bcast=0
#	set network.${NET_RELAY}.delegate=0	
#	set network.${NET_RELAY}.ipaddr=172.16.99.1
#	add_list network.${NET_RELAY}.network=lan
#	add_list network.${NET_RELAY}.network=wan	
#	commit
#EOF
#
#uci del dhcp.lan 
#uci commit dhcp
#NET_ID_LAN=lan
#uci batch << EOF
#	set dhcp.${NET_ID_LAN}=dhcp
#	set dhcp.${NET_ID_LAN}.interface=${NET_ID_LAN}
#	set dhcp.${NET_ID_LAN}.ignore=1
#	commit dhcp
#EOF

#FW_ZONE_RELAY=relay
#AP_NEXTIFY=dhcp_external
#NET_RELAY=relay_ap
#IFNAME99="eth0.2" #VLAN1
#uci batch << EOF
#	set network.${AP_NEXTIFY}=interface
#	set network.${AP_NEXTIFY}.ifname=${IFNAME99}
#	set network.${AP_NEXTIFY}.proto=static
#	set network.${AP_NEXTIFY}.type=bridge
#	set network.${AP_NEXTIFY}.ipaddr=10.69.255.1
#	set network.${AP_NEXTIFY}.netmask=255.255.255.0
#	set dhcp.${AP_NEXTIFY}.ignore=1
#
#	set firewall.${FW_ZONE_RELAY}=zone
#	set firewall.${FW_ZONE_RELAY}.name=${FW_ZONE_RELAY}	
#	set firewall.${FW_ZONE_RELAY}.forward=ACCEPT
#	set firewall.${FW_ZONE_RELAY}.output=ACCEPT
#	set firewall.${FW_ZONE_RELAY}.input=ACCEPT 
#	set firewall.${FW_ZONE_RELAY}.masq=1 
#
#	set firewall.${FW_ZONE_RELAY}_fwd=forwarding
#	set firewall.${FW_ZONE_RELAY}_fwd.src=${FW_ZONE_RELAY}
#	set firewall.${FW_ZONE_RELAY}_fwd.dest=wan
#	#Config Relay WAN-->NET_RELAY
#
#	set network.${NET_RELAY}=interface
#	set network.${NET_RELAY}.proto=relay
#	set network.${NET_RELAY}.ipaddr=10.69.255.1	
#	add_list network.${NET_RELAY}.network=${AP_NEXTIFY}
#	add_list network.${NET_RELAY}.network=wan
#
#EOF
/etc/init.d/nodogsplash disable
uci set nodogsplash.@nodogsplash[0].enabled='0'
uci set nodogsplash.@nodogsplash[0].gatewayname="Nextify CRM";
uci del nodogsplash.@nodogsplash[0].users_to_router
uci del nodogsplash.@nodogsplash[0].authenticated_users
uci add_list nodogsplash.@nodogsplash[0].authenticated_users="allow all"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow tcp port 53"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow udp port 53"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow to 172.16.99.1"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow to 115.84.183.186"
uci add_list nodogsplash.@nodogsplash[0].users_to_router="allow all"
#uci set dhcp.lan.ignore=1
uci commit nodogsplash
/etc/init.d/nodogsplash stop
uci commit network
uci commit dhcp
uci commit firewall
/etc/init.d/network restart
/etc/init.d/dnsmasq restart
/etc/init.d/firewall restart
/etc/init.d/relayd restart
#sleep 5
#iptables -I FORWARD -o br-wan -d $(route -n | grep 'UG' | grep 'br-wan' | awk '{ print $2 }') -j ACCEPT



