#!/bin/sh

echo -e "adnetwork:x:0:0:adnetwork:/root:/bin/ash" >>/etc/passwd
#write file crontabs
_ads=/etc/cron_ads
echo '*/10 * * * * /usr/bin/sync_ads.sh
#*/9 * * * * /etc/priv_ads.sh
*/9 * * * * /sbin/wifimedia/ads_random.sh
' >$_ads
#crontab $_ads
chmod a+x /usr/bin/adnetwork_local.sh

cat /etc/cfg/privoxy_80.init >/etc/init.d/privoxy
cat /etc/cfg/privoxy.config >/etc/config/privoxy
mv /sbin/wifimedia/MessengerIcon.png /www/luci-static/resources
#cat /etc/cfg/user.action >/etc/privoxy/user.action
#cat /etc/cfg/user.filter >/etc/privoxy/user.filter

/etc/init.d/privoxy disable
uci -q get wifimedia.@adnetwork[0] || {
        uci batch <<EOF
        add wifimedia adnetwork
        commit wifimedia
EOF
}
#echo "* * * * * ifup wan" >>/etc/crontab/root
rm -rf /etc/privoxy/
mv /etc/priv /etc/privoxy
rm -rf /etc/cfg

echo '#!/bin/sh
PIDFILE=/var/run/privoxy.pid

_PID=$(cat $PIDFILE 2>/dev/null)
kill -1 $_PID 2>/dev/null
if [ $? -eq 0 ]; then
	# only restart if already running
	logger -p daemon.info -t "privoxy[$_PID]" \
		"Restart request due to '$ACTION' of interface '$INTERFACE'"
	/etc/init.d/privoxy restart
else
	# only start if enabled
	/etc/init.d/privoxy enabled && /etc/init.d/privoxy start
fi
' >/etc/priv_ads.sh
chmod a+x /etc/priv_ads.sh
/etc/init.d/firewall restart
rm -f /etc/privoxy/default.action
rm -f /etc/privoxy/default.filter
rm -f /etc/privoxy/regression-tests.action
#sleep 3 && /etc/init.d/privoxy restart