#!/bin/sh /etc/rc.common

START=99
STOP=15

EXTRA_COMMANDS="status"
EXTRA_HELP="        status  checking"
lcs=/etc/opt/wfm_lcs
boot() {	
	if [ -e "$lcs" ];then
		/sbin/wifimedia/controller.sh license_srv >/dev/null 2>&1
	fi

}
