#!/bin/sh /etc/rc.common

START=99
STOP=15

boot() {
	/sbin/wifimedia/controller.sh license_srv >/dev/null 2>&1
	/sbin/wifimedia/controller.sh checking
	/sbin/wifimedia/controller.sh action_lan_wlan
}
